### ISSUE TITLE
pause function

### ISSUE THREAD

**Issue by splch** [spencerchurchill/BareBones-MIDI-Player#1]
you need to add a pause function.

[http://www.midijs.net/midijs_api.html](http://www.midijs.net/midijs_api.html)

```
// Define a function to handle player events
function display_time(ev) {
     my_time_div.innerHTML = ev.time; // time in seconds, since start of playback
};

// Set the function as player callback
MIDIjs.player_callback = display_mesage;
```

possibly use this?
     pause.onclick(record the time since playback and stop playback). play.onlick(play midi from playback point)

**Comment by spencerchurchill** [comment]
time to make the switch to [https://github.com/mudcube/MIDI.js](https://github.com/mudcube/MIDI.js)

**Comment by splch** [comment]
resolved with the recent update to MIDIjs
